"use strict";

// Popup copy rules (see ui/panels.js showUpgPop):
//   flavor  - optional, italic, the only place for metaphor.
//   desc()  - OPTIONAL, one plain sentence, ONLY for what Now/Next cannot show (conditions,
//             timers, resets, trade-offs). If the name + Now/Next already say it, there is no desc.
//   now(l)  - the total bonus AT level l. The popup renders "Now: now(lvl)" (hidden at level 0)
//             and "Next: now(lvl+1)" (hidden at max). Standard units: "+X ✦ per pulse",
//             "+X ✦ per orbit", "+X% orbit speed", "xN.NN <target> payout", "xN payout burst every M orbits".
const UPGRADES = [
  {
    id: "touch",
    name: "Cosmic Pulse",
    maxLevel: 8,
    section: "MAIN",
    costs: [10, 50, 120, 250, 580, 1000, 1850, 3000],
    flavor: "Maw stirs, drawing a slow, steady breath of light.",
    desc: () => "Maw pulses every second, generating stardust.",
    now: (l) => `+${5 * l} ✦ per pulse`,
    unlock: () => true,
  },
  {
    id: "surge",
    name: "Pulse Surge",
    maxLevel: 5,
    section: "MAIN",
    costs: [1200, 2200, 3600, 6300, 10000],
    flavor: "Each breath reaches deeper, and takes more.",
    now: (l) => `+${10 * l} ✦ per pulse`,
    unlock: () => lvl("touch") >= 6,
  },
  {
    id: "afterglow",
    name: "Afterglow",
    maxLevel: 5,
    section: "MAIN",
    costs: [2500, 4500, 8000, 13000, 22000],
    flavor: "Catch the light, and Maw keeps its warmth a while.",
    desc: () => "Active for 60s after catching a comet. Another catch refreshes it.",
    now: (l) => `+${20 * l} ✦ per pulse`,
    unlock: () => lvl("touch") >= 6,
  },
  {
    id: "deepbreath",
    name: "Deep Breath",
    maxLevel: 8,
    section: "MAIN",
    costs: [2500, 6000, 13000, 27000, 55000, 110000, 220000, 430000],
    flavor: "Now and then Maw draws a deeper breath, and takes twice as much.",
    now: (l) => `every ${13 - l}th pulse pays x${deepBreathMult().toFixed(1)}`,
    unlock: () => G.runDust >= 10000,
  },
  {
    id: "abyssal",
    name: "Abyssal Breath",
    maxLevel: 15,
    section: "MAIN",
    costs: [
      3000, 5000, 8000, 13000, 20000, 31000, 49000, 77000, 120000, 185000,
      290000, 450000, 700000, 1100000, 1700000,
    ],
    flavor: "Each deep breath reaches further down, into the dark Maw keeps.",
    now: (l) => `Deep Breaths pay x${(2 + 0.2 * l).toFixed(1)}`,
    unlock: () => G.runDust >= 10000,
  },
  {
    id: "gravpull",
    name: "Gravitational Pull",
    maxLevel: 5,
    section: "MAIN",
    costs: [12000, 35000, 120000, 475000, 1850000],
    flavor: "Let the gathered weight do some of the pulling.",
    desc: () => "Every pulse gains a share of total orbiter payout.",
    now: (l) => `+${l}% (+✦${fmtNum(Math.round(0.01 * l * orbiterPayoutSum()))} per pulse)`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "resonance",
    name: "Resonance",
    maxLevel: 5,
    section: "MAIN",
    costs: [14000, 27000, 57000, 150000, 365000],
    flavor: "Tune the whole quiet system until it hums.",
    desc: () => "Maw's glow brightens with each level.",
    now: (l) => `+${10 * l}% all orbiter payout`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "dust",
    name: "Dust Particle",
    maxLevel: 1,
    section: "DUST PARTICLES",
    costs: [100],
    flavor: "The first grain of dust to settle into Maw's quiet orbit.",
    desc: () => "Adds the first dust particle on the inner orbit.",
    now: () => `✦10 base payout per orbit`,
    unlock: () => lvl("touch") >= 2,
  },
  {
    id: "dustcount",
    name: "Dust Particle Count",
    maxLevel: 4,
    section: "DUST PARTICLES",
    costs: [600, 1500, 4000, 9200],
    now: (l) => `${1 + l} particles total`,
    unlock: () => lvl("dust") >= 1,
  },
  {
    id: "dustpay",
    name: "Dust Particle Payout",
    maxLevel: 5,
    section: "DUST PARTICLES",
    costs: [200, 800, 2500, 5600, 14500],
    now: (l) => `+${10 * l} ✦ per particle`,
    unlock: () => lvl("dust") >= 1,
  },
  {
    id: "dustspd",
    name: "Dust Particle Speed",
    maxLevel: 5,
    section: "DUST PARTICLES",
    costs: [250, 1000, 3000, 7500, 16000],
    mult: (lvl) => 1 + 0.2 * lvl,
    now: (l) => `+${20 * l}% orbit speed`,
    unlock: () => lvl("dust") >= 1,
  },
  {
    id: "coagulation",
    name: "Coagulation",
    maxLevel: 5,
    section: "DUST PARTICLES",
    identity: true,
    group: "dust",
    costs: [10000, 23000, 48000, 90000, 170000],
    flavor: "Grains collide and stick - the first step toward worlds.",
    now: (l) => `+${15 * l} ✦ per particle, +${50 * l} ✦ to the Asteroid`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "iceMantles",
    name: "Ice Mantles",
    maxLevel: 5,
    section: "DUST PARTICLES",
    identity: true,
    group: "dust",
    costs: [10000, 23000, 48000, 90000, 170000],
    flavor: "Past the frost line, the grains gather ice.",
    now: (l) => `+${5 * l} ✦ per particle, +${150 * l} ✦ to the Moon`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "denser",
    name: "Denser Grains",
    maxLevel: 5,
    section: "DUST PARTICLES",
    identity: true,
    group: "dust",
    costs: [10000, 23000, 48000, 90000, 170000],
    flavor: "Heavier, darker grains that carry more each pass.",
    now: (l) => `x${(1 + 0.15 * l).toFixed(2)} dust payout`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "dustdevil",
    name: "Dust Devil",
    maxLevel: 3,
    section: "DUST PARTICLES",
    identity: true,
    group: "dust",
    costs: [15000, 40000, 100000],
    flavor: "The swarm winds into a tightening whirl.",
    desc: () => "Starts at 0% each universe, reaches full after 10 minutes.",
    now: (l) => `up to +${8 * l}% dust payout`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "prdrag",
    name: "Poynting-Robertson Drag",
    maxLevel: 3,
    section: "DUST PARTICLES",
    identity: true,
    group: "dust",
    costs: [15000, 40000, 100000],
    flavor: "Starlight drags the grains inward, one by one, into Maw.",
    desc: () => "A grain falls into Maw, pays, then grows back.",
    now: (l) => `every ${9 - 2 * l}s, x${4 + 2 * l} payout`,
    unlock: () => G.runDust >= 50000,
  },
  {
    id: "asteroid",
    name: "Asteroid",
    maxLevel: 1,
    section: "ASTEROID",
    costs: [2000],
    flavor: "A wandering chunk of old rock, heavy and slow.",
    desc: () => "Adds the asteroid on a wider, slower orbit.",
    now: () => `✦50 base payout per orbit`,
    unlock: () => G.runDust >= 5000,
  },
  {
    id: "astpay",
    name: "Asteroid Payout",
    maxLevel: 5,
    section: "ASTEROID",
    costs: [2500, 4500, 10500, 24000, 58000],
    now: (l) => `+${50 * l} ✦ per orbit`,
    unlock: () => lvl("asteroid") >= 1,
  },
  {
    id: "astspd",
    name: "Asteroid Speed",
    maxLevel: 5,
    section: "ASTEROID",
    costs: [3000, 6000, 13000, 28000, 62000],
    mult: (lvl) => 1 + 0.2 * lvl,
    now: (l) => `+${20 * l}% orbit speed`,
    unlock: () => lvl("asteroid") >= 1,
  },
  {
    id: "astcomp",
    name: "Asteroid Composition",
    maxLevel: 5,
    section: "ASTEROID",
    costs: [3500, 11000, 26000, 60000, 135000],
    flavor: "Reforge the rock into denser, richer stuff.",
    now: (l) => `${ASTEROID_COMP.names[l]}: x${ASTEROID_COMP.mult[l]} payout`,
    unlock: () => lvl("asteroid") >= 1,
  },
  {
    id: "rubblepile",
    name: "Rubble Pile",
    maxLevel: 5,
    section: "ASTEROID",
    identity: true,
    group: "asteroid",
    costs: [12000, 26000, 52000, 95000, 170000],
    flavor: "A loose heap of gravel, bound only by its own faint gravity.",
    now: (l) => `+${40 * l} ✦ per dust particle owned`,
    unlock: () => lvl("asteroid") >= 1 && G.runDust >= 100000,
  },
  {
    id: "ferropulse",
    name: "Ferromagnetic Pulse",
    maxLevel: 5,
    section: "ASTEROID",
    identity: true,
    group: "asteroid",
    costs: [12000, 26000, 52000, 95000, 170000],
    flavor: "Veins of iron ring with Maw's every beat.",
    now: (l) => `+${15 * l} ✦ per pulse`,
    unlock: () => lvl("asteroid") >= 1 && G.runDust >= 100000,
  },
  {
    id: "meteorshower",
    name: "Meteor Shower",
    maxLevel: 3,
    section: "ASTEROID",
    identity: true,
    group: "asteroid",
    costs: [20000, 50000, 120000],
    flavor: "The rock keeps shedding debris that rains inward.",
    desc: () => "No payout of its own.",
    now: (l) => `comets arrive ${Math.round((1 - Math.pow(0.85, l)) * 100)}% sooner`,
    unlock: () => lvl("asteroid") >= 1 && G.runDust >= 100000,
  },
  {
    id: "prospector",
    name: "Prospector's Cut",
    maxLevel: 5,
    section: "ASTEROID",
    identity: true,
    group: "asteroid",
    costs: [12000, 26000, 52000, 95000, 170000],
    flavor: "Skip the smelter. Sell the raw shine to passing comets.",
    desc: () => "Turns off the Composition multiplier.",
    now: (l) => `comet windfall x${(1 + 0.15 * l).toFixed(2)}`,
    unlock: () => lvl("asteroid") >= 1 && G.runDust >= 100000,
  },
  {
    id: "slingshot",
    name: "Gravitational Slingshot",
    maxLevel: 3,
    section: "ASTEROID",
    identity: true,
    group: "asteroid",
    costs: [20000, 50000, 120000],
    flavor: "Wind up on the deep gravity, then let go.",
    now: (l) => `x${2 + l} payout burst every 6 orbits`,
    unlock: () => lvl("asteroid") >= 1 && G.runDust >= 100000,
  },
  {
    id: "moon",
    name: "Moon",
    maxLevel: 1,
    section: "MOON",
    costs: [10000],
    flavor: "A pale companion, heavy enough to hold its own slow circle.",
    desc: () => "Adds the moon on a wide, slow orbit. Payout follows the phase: low at the new moon, high at the full.",
    now: () => `✦200 base payout per orbit`,
    unlock: () => G.runDust >= 32000,
  },
  {
    id: "moonpay",
    name: "Moon Payout",
    maxLevel: 5,
    section: "MOON",
    costs: [15000, 50000, 150000, 330000, 600000],
    now: (l) => `+${200 * l} ✦ per orbit`,
    unlock: () => lvl("moon") >= 1,
  },
  {
    id: "moonspd",
    name: "Moon Speed",
    maxLevel: 5,
    section: "MOON",
    costs: [20000, 80000, 200000, 385000, 700000],
    mult: (lvl) => 1 + 0.2 * lvl,
    now: (l) => `+${20 * l}% orbit speed`,
    unlock: () => lvl("moon") >= 1,
  },
  {
    id: "moonphase",
    name: "Lunar Phases",
    maxLevel: 5,
    section: "MOON",
    costs: [12000, 28000, 55000, 90000, 175000],
    flavor: "Learn the tides the moon answers to, and widen them.",
    now: (l) => `x${(0.75 + 0.1 * l).toFixed(2)} new moon .. x${(1.25 + 0.1 * l).toFixed(2)} full moon`,
    unlock: () => lvl("moon") >= 1,
  },
  {
    id: "albedo",
    name: "Albedo",
    maxLevel: 5,
    section: "MOON",
    identity: true,
    group: "moon",
    costs: [15000, 32000, 64000, 120000, 220000],
    flavor: "A brighter face throws back more of the light.",
    now: (l) => `x${(1 + 0.10 * l).toFixed(2)} moon payout`,
    unlock: () => lvl("moon") >= 1 && G.runDust >= 150000,
  },
  {
    id: "springtide",
    name: "Spring Tide",
    maxLevel: 5,
    section: "MOON",
    identity: true,
    group: "moon",
    costs: [15000, 32000, 64000, 120000, 220000],
    flavor: "When the moon runs full, its tides pull with Maw.",
    desc: () => "Strongest at the full moon, zero at the new.",
    now: (l) => `up to +${20 * l} ✦ per pulse`,
    unlock: () => lvl("moon") >= 1 && G.runDust >= 150000,
  },
  {
    id: "eclipse",
    name: "Solar Eclipse",
    maxLevel: 3,
    section: "MOON",
    identity: true,
    group: "moon",
    costs: [30000, 70000, 150000],
    flavor: "Now and then the moon slides across Maw and swallows the light.",
    now: (l) => `x10 payout burst every ${6 - l} orbits`,
    unlock: () => lvl("moon") >= 1 && G.runDust >= 150000,
  },
  {
    id: "standstill",
    name: "Lunar Standstill",
    maxLevel: 1,
    section: "MOON",
    identity: true,
    group: "moon",
    costs: [30000],
    flavor: "Every long while the moon holds still at the far edge of its wander.",
    desc: () => lvl("standstill") >= 1 && typeof standstillOrbitsLeft === "function"
        ? `Orbits left: ${standstillOrbitsLeft()}.` : "",
    now: () => `x40 payout burst every 16 orbits`,
    unlock: () => lvl("moon") >= 1 && G.runDust >= 150000,
  },
  {
    id: "bloodmoon",
    name: "Blood Moon",
    maxLevel: 5,
    section: "MOON",
    identity: true,
    group: "moon",
    costs: [15000, 32000, 64000, 120000, 220000],
    flavor: "Deepen the gamble: nothing at the new, everything at the full.",
    desc: () => "Average payout stays the same.",
    now: (l) => `x${Math.max(0, 0.75 + 0.1 * lvl("moonphase") - 0.15 * l).toFixed(2)} new moon .. x${(1.25 + 0.1 * lvl("moonphase") + 0.15 * l).toFixed(2)} full moon`,
    unlock: () => lvl("moon") >= 1 && G.runDust >= 150000,
  },
  {
    id: "dwarf",
    name: "Dwarf Planet",
    maxLevel: 1,
    section: "DWARF PLANET",
    costs: [50000],
    flavor: "A captured world settles into the widest, calmest orbit.",
    desc: () => "Adds the Dwarf Planet on the widest, slowest orbit.",
    now: () => `✦800 base payout per orbit`,
    unlock: () =>
      typeof singularityLevel === "function" && singularityLevel() >= 1,
  },
  {
    id: "dwarfpay",
    name: "Dwarf Planet Payout",
    maxLevel: 5,
    section: "DWARF PLANET",
    costs: [50000, 130000, 320000, 700000, 1200000],
    now: (l) => `+${800 * l} ✦ per orbit`,
    unlock: () => lvl("dwarf") >= 1,
  },
  {
    id: "dwarfcompound",
    name: "Compounding Orbit",
    maxLevel: 3,
    section: "DWARF PLANET",
    costs: [120000, 300000, 700000],
    flavor: "Each slow lap settles a little more stardust into its orbit.",
    desc: () => "Payout grows +0.3% every orbit up to the cap. Restarts every universe.",
    now: (l) => `cap +${[0, 15, 30, 50][l]}%`,
    unlock: () => lvl("dwarf") >= 1,
  },
  {
    id: "dwarftrojan",
    name: "Trojan Companions",
    maxLevel: 2,
    section: "DWARF PLANET",
    costs: [250000, 700000],
    desc: () => "Each companion pays 1/8 of the Dwarf Planet's payout.",
    now: (l) => `${l} companion${l === 1 ? "" : "s"}`,
    unlock: () => lvl("dwarf") >= 1,
  },
  {
    id: "glacial",
    name: "Glacial Orbit",
    maxLevel: 1,
    section: "DWARF PLANET",
    identity: true,
    group: "dwarf",
    costs: [80000],
    flavor: "Ember slows to a crawl, and each pass lands with far more weight.",
    desc: () => "Bigger single payouts; income per minute barely changes.",
    now: () => `x0.5 speed, x2.05 payout`,
    unlock: () => lvl("dwarf") >= 1 && G.runDust >= 200000,
  },
  {
    id: "distantkin",
    name: "Distant Kin",
    maxLevel: 3,
    section: "DWARF PLANET",
    identity: true,
    group: "dwarf",
    costs: [60000, 140000, 300000],
    flavor: "A cold kinship with the deep cosmos calls the Vortex in.",
    desc: () => "No payout of its own.",
    now: (l) => `Vortex ${Math.round((1 - Math.pow(0.8, l)) * 100)}% sooner, pays x${(1 + 0.25 * l).toFixed(2)}`,
    unlock: () => lvl("dwarf") >= 1 && G.runDust >= 200000,
  },
  {
    id: "longnow",
    name: "The Long Now",
    maxLevel: 3,
    section: "DWARF PLANET",
    identity: true,
    group: "dwarf",
    costs: [60000, 140000, 300000],
    flavor: "The slow world rewards a slow, patient universe.",
    desc: () => "Payout grows +0.3% every orbit up to the cap. Restarts every universe.",
    now: (l) => `cap +${10 * l}%`,
    unlock: () => lvl("dwarf") >= 1 && G.runDust >= 200000,
  },
  {
    id: "storedwinter",
    name: "Stored Winter",
    maxLevel: 3,
    section: "DWARF PLANET",
    identity: true,
    group: "dwarf",
    costs: [60000, 140000, 300000],
    flavor: "Ember banks the cold, then lets it go all at once.",
    desc: () => "Ember releases the whole bank each pass.",
    now: (l) => `banks ${20 * l}% of every pulse`,
    unlock: () => lvl("dwarf") >= 1 && G.runDust >= 200000,
  },
  {
    id: "anchor",
    name: "Gravitational Anchor",
    maxLevel: 3,
    section: "DWARF PLANET",
    identity: true,
    group: "dwarf",
    costs: [60000, 140000, 300000],
    flavor: "Ember's mass steadies every orbit in the system.",
    now: (l) => `+${5 * l}% all orbiter payout`,
    unlock: () => lvl("dwarf") >= 1 && G.runDust >= 200000,
  },
  {
    id: "charm",
    name: "Comet Charm",
    maxLevel: 3,
    section: "COMETS",
    costs: [30, 80, 200],
    now: (l) => `comet windfall x${(1 + 0.25 * l).toFixed(2)}`,
    unlock: () => false,
  },
];

const SECTION_ORDER = [
  "MAIN",
  "DUST PARTICLES",
  "ASTEROID",
  "MOON",
  "DWARF PLANET",
  "COMETS",
];

// Identity upgrades are limited per `group`: a group lets you pick up to IDENTITY_PICKS[group]
// distinct identities per universe; once that many are chosen, the rest lock. Dust picks 1 of 3;
// the orbiter groups pick 2 of 5.
const IDENTITY_PICKS = { dust: 2, asteroid: 2, moon: 2, dwarf: 2 };

function identityChosenCount(group) {
  return UPGRADES.reduce((n, x) => n + (x.group === group && (G.upgrades[x.id] || 0) >= 1 ? 1 : 0), 0);
}

// Returns the id of a chosen identity locking `u` (truthy), or null if `u` is free to buy/level.
function identityLockedBy(u) {
  if (!u || !u.group) return null;
  if ((G.upgrades[u.id] || 0) >= 1) return null;                       // u itself already chosen -> free to level
  const limit = IDENTITY_PICKS[u.group] || 1;
  if (identityChosenCount(u.group) < limit) return null;               // still room to pick another
  const chosen = UPGRADES.find((x) => x.group === u.group && x.id !== u.id && (G.upgrades[x.id] || 0) >= 1);
  return chosen ? chosen.id : true;                                    // limit reached, u is not chosen -> locked
}
